### ISSUE TITLE
Redis 缓存相关导致报错

### ISSUE THREAD

**Issue by inkss** [ArtalkJS/ArtalkGo#26]
突然间，无法登录了，相关日志：

```
Artalk (2.1.4/2ad6864)

 -> A Selfhosted Comment System.
 -> https://artalk.js.org

-------------------------------

⇨ http server started on [::]:23366
echo: http: panic serving 127.0.0.1:38796: interface conversion: interface {} is string, not []uint8
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc00026cd20)
	/usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x14d4a00, 0xc0007f6b70)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/ArtalkJS/ArtalkGo/http.getActionLastTime(0x1927aa8, 0xc00024abe0, 0x157f5a0, 0xc0008f0cc0, 0x16a72c7)
	/go/src/github.com/ArtalkJS/ArtalkGo/http/permission.go:163 +0x189
github.com/ArtalkJS/ArtalkGo/http.IsActionInTimeFrame(0x1927aa8, 0xc00024abe0, 0xc000896600)
	/go/src/github.com/ArtalkJS/ArtalkGo/http/permission.go:150 +0x39
github.com/ArtalkJS/ArtalkGo/http.IsReqNeedCaptchaCheck(0x1927aa8, 0xc00024abe0, 0xd)
	/go/src/github.com/ArtalkJS/ArtalkGo/http/permission.go:127 +0x105
github.com/ArtalkJS/ArtalkGo/http.ActionLimitMiddleware.func1.1(0x1927aa8, 0xc00024abe0, 0xc0000e0000, 0x0)
	/go/src/github.com/ArtalkJS/ArtalkGo/http/permission.go:59 +0x1f7
github.com/onrik/logrus/echo.Middleware.func1.1(0x1927aa8, 0xc00024abe0, 0x16b7df2, 0x1b)
	/go/pkg/mod/github.com/onrik/logrus@v0.9.0/echo/middleware.go:62 +0x16e
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0x1927aa8, 0xc00024abe0, 0x3, 0x4)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/middleware/cors.go:186 +0x1016
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000662480, 0x1904a28, 0xc00087f180, 0xc00084ec00)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/echo.go:654 +0x2bc
net/http.serverHandler.ServeHTTP(0xc000182e00, 0x1904a28, 0xc00087f180, 0xc00084ec00)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc00026cd20, 0x1909fd0, 0xc000755280)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
```

**Comment by inkss** [comment]
redis 里执行了 flushall 好了，具体得靠你来分析了。

**Comment by inkss** [comment]
然后。。。 又出问题了，我换成 builtin 了。

**Comment by qwqcode** [comment]
看来这个 Redis 缓存还是需要进一步测试呀

**Comment by qwqcode** [comment]
已修复 https://github.com/ArtalkJS/ArtalkGo/commit/3120b813b9fd2eb1dfb3c126e1c3a044e087f91a

**Comment by inkss** [comment]
升级链接的下载地址能不能换一个，境内服务器访问github完全随缘

**Comment by qwqcode** [comment]
你可以挂个梯子。GitHub 白嫖，国内流量费太贵了

**Comment by inkss** [comment]
增加个访问 unpkg.com 的设置？

![Snipper - Snipaste_22-04-27_18-19-17](https://user-images.githubusercontent.com/31947043/165497142-94f0d8bc-f722-45f3-9695-0ebdd6dc3842.png)

**Comment by inkss** [comment]
或者加个进度条吧，我还以为卡了呢

**Comment by qwqcode** [comment]
用 Docker 可以换源

**Comment by inkss** [comment]
有没有特殊的依赖环境，就没用docker部署

**Comment by chuyua** [comment]
本地的redis 感觉现在效果不如默认的 看大佬喜欢那个就开发那个吧
